# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.mainWidget = QtWidgets.QWidget(MainWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.centralPanel = QtWidgets.QWidget(self.mainWidget)
        self.centralPanel.setGeometry(QtCore.QRect(100, 160, 274, 282))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralPanel.sizePolicy().hasHeightForWidth())
        self.centralPanel.setSizePolicy(sizePolicy)
        self.centralPanel.setObjectName("centralPanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralPanel)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralPanel)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableSortDropDown = QtWidgets.QComboBox(self.frame)
        self.tableSortDropDown.setObjectName("tableSortDropDown")
        self.tableSortDropDown.addItem("")
        self.tableSortDropDown.addItem("")
        self.tableSortDropDown.addItem("")
        self.tableSortDropDown.addItem("")
        self.horizontalLayout.addWidget(self.tableSortDropDown)
        self.tableSortDirDropDown = QtWidgets.QComboBox(self.frame)
        self.tableSortDirDropDown.setObjectName("tableSortDirDropDown")
        self.tableSortDirDropDown.addItem("")
        self.tableSortDirDropDown.addItem("")
        self.horizontalLayout.addWidget(self.tableSortDirDropDown)
        self.verticalLayout.addWidget(self.frame)
        self.tableSearchBar = QtWidgets.QLineEdit(self.centralPanel)
        self.tableSearchBar.setClearButtonEnabled(True)
        self.tableSearchBar.setObjectName("tableSearchBar")
        self.verticalLayout.addWidget(self.tableSearchBar)
        self.videoTable = QtWidgets.QTableView(self.centralPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoTable.sizePolicy().hasHeightForWidth())
        self.videoTable.setSizePolicy(sizePolicy)
        self.videoTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.videoTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.videoTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.videoTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.videoTable.setSortingEnabled(False)
        self.videoTable.setCornerButtonEnabled(True)
        self.videoTable.setObjectName("videoTable")
        self.videoTable.horizontalHeader().setCascadingSectionResizes(False)
        self.videoTable.horizontalHeader().setDefaultSectionSize(120)
        self.videoTable.horizontalHeader().setHighlightSections(True)
        self.videoTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.videoTable)
        MainWindow.setCentralWidget(self.mainWidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_playlists = QtWidgets.QAction(MainWindow)
        self.actionImport_playlists.setObjectName("actionImport_playlists")
        self.actionManage_tags = QtWidgets.QAction(MainWindow)
        self.actionManage_tags.setObjectName("actionManage_tags")
        self.menuImport.addAction(self.actionImport_playlists)
        self.menuImport.addAction(self.actionManage_tags)
        self.menubar.addAction(self.menuImport.menuAction())

        self.retranslateUi(MainWindow)
        self.tableSortDropDown.setCurrentIndex(1)
        self.tableSortDirDropDown.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YT Saved Videos"))
        self.tableSortDropDown.setItemText(0, _translate("MainWindow", "publish date"))
        self.tableSortDropDown.setItemText(1, _translate("MainWindow", "save date"))
        self.tableSortDropDown.setItemText(2, _translate("MainWindow", "video title"))
        self.tableSortDropDown.setItemText(3, _translate("MainWindow", "channel title"))
        self.tableSortDirDropDown.setItemText(0, _translate("MainWindow", "ascending"))
        self.tableSortDirDropDown.setItemText(1, _translate("MainWindow", "descending"))
        self.tableSearchBar.setToolTip(_translate("MainWindow", "Press enter to filter table"))
        self.tableSearchBar.setPlaceholderText(_translate("MainWindow", "Search table"))
        self.menuImport.setTitle(_translate("MainWindow", "File"))
        self.actionImport_playlists.setText(_translate("MainWindow", "Import playlists"))
        self.actionManage_tags.setText(_translate("MainWindow", "Manage tags"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
