# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/tagManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TagManager(object):
    def setupUi(self, TagManager):
        TagManager.setObjectName("TagManager")
        TagManager.resize(491, 489)
        TagManager.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(TagManager)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboFrame = QtWidgets.QFrame(TagManager)
        self.comboFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.comboFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.comboFrame.setObjectName("comboFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.comboFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tagTypeDropDown = QtWidgets.QComboBox(self.comboFrame)
        self.tagTypeDropDown.setObjectName("tagTypeDropDown")
        self.tagTypeDropDown.addItem("")
        self.tagTypeDropDown.addItem("")
        self.horizontalLayout_2.addWidget(self.tagTypeDropDown)
        self.tagSortDropDown = QtWidgets.QComboBox(self.comboFrame)
        self.tagSortDropDown.setObjectName("tagSortDropDown")
        self.tagSortDropDown.addItem("")
        self.tagSortDropDown.addItem("")
        self.horizontalLayout_2.addWidget(self.tagSortDropDown)
        self.tagSortDirDropDown = QtWidgets.QComboBox(self.comboFrame)
        self.tagSortDirDropDown.setObjectName("tagSortDirDropDown")
        self.tagSortDirDropDown.addItem("")
        self.tagSortDirDropDown.addItem("")
        self.horizontalLayout_2.addWidget(self.tagSortDirDropDown)
        self.verticalLayout.addWidget(self.comboFrame)
        self.tagSearchBar = QtWidgets.QLineEdit(TagManager)
        self.tagSearchBar.setClearButtonEnabled(True)
        self.tagSearchBar.setObjectName("tagSearchBar")
        self.verticalLayout.addWidget(self.tagSearchBar)
        self.tagList = QtWidgets.QListView(TagManager)
        self.tagList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tagList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tagList.setObjectName("tagList")
        self.verticalLayout.addWidget(self.tagList)
        self.buttonFrame = QtWidgets.QFrame(TagManager)
        self.buttonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonFrame.setObjectName("buttonFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttonFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.removeTagButton = QtWidgets.QPushButton(self.buttonFrame)
        self.removeTagButton.setCheckable(False)
        self.removeTagButton.setChecked(False)
        self.removeTagButton.setAutoDefault(False)
        self.removeTagButton.setFlat(False)
        self.removeTagButton.setObjectName("removeTagButton")
        self.horizontalLayout.addWidget(self.removeTagButton)
        self.okButton = QtWidgets.QPushButton(self.buttonFrame)
        self.okButton.setAutoDefault(False)
        self.okButton.setDefault(False)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.applyButton = QtWidgets.QPushButton(self.buttonFrame)
        self.applyButton.setAutoDefault(False)
        self.applyButton.setObjectName("applyButton")
        self.horizontalLayout.addWidget(self.applyButton)
        self.cancelButton = QtWidgets.QPushButton(self.buttonFrame)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addWidget(self.buttonFrame)

        self.retranslateUi(TagManager)
        QtCore.QMetaObject.connectSlotsByName(TagManager)

    def retranslateUi(self, TagManager):
        _translate = QtCore.QCoreApplication.translate
        TagManager.setWindowTitle(_translate("TagManager", "Tag Manager"))
        self.tagTypeDropDown.setItemText(0, _translate("TagManager", "tags"))
        self.tagTypeDropDown.setItemText(1, _translate("TagManager", "yt tags"))
        self.tagSortDropDown.setItemText(0, _translate("TagManager", "by name"))
        self.tagSortDropDown.setItemText(1, _translate("TagManager", "by video count"))
        self.tagSortDirDropDown.setItemText(0, _translate("TagManager", "ascending"))
        self.tagSortDirDropDown.setItemText(1, _translate("TagManager", "descending"))
        self.tagSearchBar.setToolTip(_translate("TagManager", "Filter tag list by typing"))
        self.tagSearchBar.setPlaceholderText(_translate("TagManager", "Search tags"))
        self.removeTagButton.setText(_translate("TagManager", "Remove tag"))
        self.okButton.setText(_translate("TagManager", "OK"))
        self.applyButton.setText(_translate("TagManager", "Apply"))
        self.cancelButton.setText(_translate("TagManager", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TagManager = QtWidgets.QDialog()
    ui = Ui_TagManager()
    ui.setupUi(TagManager)
    TagManager.show()
    sys.exit(app.exec_())
